development:
  adapter: postgresql
  encoding: unicode
  database: jakd_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: jakd_production
  pool: 5
  username: postgres
  password: